controller_list:
  - name: fake_arm_controller
    joints:
      - meca_axis_1_joint
      - meca_axis_2_joint
      - meca_axis_3_joint
      - meca_axis_4_joint
      - meca_axis_5_joint
initial:  # Define initial robot poses.
  - group: arm
    pose: hoome