# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  meca_axis_1_joint:
    has_velocity_limits: true
    max_velocity: 2.61799
    has_acceleration_limits: false
    max_acceleration: 0
  meca_axis_2_joint:
    has_velocity_limits: true
    max_velocity: 2.61799
    has_acceleration_limits: false
    max_acceleration: 0
  meca_axis_3_joint:
    has_velocity_limits: true
    max_velocity: 3.14159
    has_acceleration_limits: false
    max_acceleration: 0
  meca_axis_4_joint:
    has_velocity_limits: true
    max_velocity: 5.23599
    has_acceleration_limits: false
    max_acceleration: 0
  meca_axis_5_joint:
    has_velocity_limits: true
    max_velocity: 5.23599
    has_acceleration_limits: false
    max_acceleration: 0
  meca_axis_6_joint:
    has_velocity_limits: true
    max_velocity: 8.726649999999999
    has_acceleration_limits: false
    max_acceleration: 0
  meca_finger_joint1:
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0
  meca_finger_joint2:
    has_velocity_limits: true
    max_velocity: 0.2
    has_acceleration_limits: false
    max_acceleration: 0