# Simulation settings for using moveit_sim_controllers
meca_500_r3:
  moveit_sim_hw_interface:
    joint_model_group: meca_arm
    joint_model_group_pose: default
  # Settings for ros_control_boilerplate control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
  # Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - meca_axis_1_joint
      - meca_axis_2_joint
      - meca_axis_3_joint
      - meca_axis_4_joint
      - meca_axis_5_joint
      - meca_axis_6_joint
    sim_control_mode: 1 # 0: position, 1: velocity
  # Publish all joint states
  # Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  controller_list:
    - name: meca_500_r3/arm_position_controller
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
        - meca_axis_1_joint
        - meca_axis_2_joint
        - meca_axis_3_joint
        - meca_axis_4_joint
        - meca_axis_5_joint
        - meca_axis_6_joint

  arm_position_controller:
    type: position_controllers/JointPositionController
    joints:
      - meca_axis_1_joint
      - meca_axis_2_joint
      - meca_axis_3_joint
      - meca_axis_4_joint
      - meca_axis_5_joint
      - meca_axis_6_joint
    gains:
      meca_axis_1_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      meca_axis_2_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      meca_axis_3_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      meca_axis_4_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      meca_axis_5_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
      meca_axis_6_joint:
        p: 100
        d: 1
        i: 1
        i_clamp: 1
