# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: meca_arm
  joint_model_group_pose: home pose
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - meca_axis_1_joint
    - meca_axis_2_joint
    - meca_axis_3_joint
    - meca_axis_4_joint
    - meca_axis_5_joint
    - meca_axis_6_joint
    - meca_finger_joint1

  sim_control_mode: 0 # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS

controller_list:
  - name: hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - meca_finger_joint1

  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - meca_axis_1_joint
      - meca_axis_2_joint
      - meca_axis_3_joint
      - meca_axis_4_joint
      - meca_axis_5_joint
      - meca_axis_6_joint
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - meca_axis_1_joint
    - meca_axis_2_joint
    - meca_axis_3_joint
    - meca_axis_4_joint
    - meca_axis_5_joint
    - meca_axis_6_joint
  gains:
    meca_axis_1_joint:
      p: 500
      d: 1
      i: 1
      i_clamp: 1
    meca_axis_2_joint:
      p: 500
      d: 1
      i: 1
      i_clamp: 1

    meca_axis_3_joint:
      p: 500
      d: 1
      i: 1
      i_clamp: 1

    meca_axis_4_joint:
      p: 500
      d: 1
      i: 1
      i_clamp: 1

    meca_axis_5_joint:
      p: 500
      d: 1
      i: 1
      i_clamp: 1

    meca_axis_6_joint:
      p: 500
      d: 1
      i: 1
      i_clamp: 1

hand_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - meca_finger_joint1

  gains:
    meca_finger_joint1:
      p: 300
      d: 2
      i: 3
      i_clamp: 1
    meca_finger_joint2:
      p: 300
      d: 2
      i: 3
      i_clamp: 1
