# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: meca_arm
  joint_model_group_pose: home pose
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - meca_axis_1_joint
    - meca_axis_2_joint
    - meca_axis_3_joint
    - meca_axis_4_joint
    - meca_axis_5_joint
    - meca_axis_6_joint
    - meca_finger_joint1
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - meca_axis_1_joint
    - meca_axis_2_joint
    - meca_axis_3_joint
    - meca_axis_4_joint
    - meca_axis_5_joint
    - meca_axis_6_joint
  gains:
    meca_axis_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    meca_axis_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    meca_axis_3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    meca_axis_4_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    meca_axis_5_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    meca_axis_6_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
hand_controller:
  type: effort_controllers/JointEffortController
  joints:
    meca_finger_joint1
  gains:
    meca_finger_joint1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1